import test from 'node:test';
import assert from 'node:assert/strict';
import '../src/model.js';
const M=globalThis.TripModel;
const dayId='2026-11-06';
function fixture(patch={}){return {dayId,slotId:'morning',title:'테스트 장소',address:'오사카',mapsUrl:M.searchUrl('테스트 장소'),category:'sight',weather:'outdoor',cost:null,duration:60,reservation:false,description:'함께 가요',photoUrl:'',lat:null,lng:null,...patch};}
function add(s=M.create(),patch={},actor='p1'){return M.change(s,{type:'add',candidate:fixture(patch)},actor);}
function action(s,type,id=s.candidates[0]?.id,actor='p1',extra={}){return M.change(s,{type,id,...extra},actor);}
test('empty trip is exactly 5 participants, 3 dates and 8 slots each',()=>{const s=M.create();assert.equal(s.participants.length,5);assert.equal(s.days.length,3);assert.deepEqual(s.days.map(d=>d.slots.length),[8,8,8]);assert.equal(s.candidates.length,0);assert.deepEqual(M.validate(s),s);});
test('multiple candidates can be voted for; same candidate toggles one vote per person',()=>{let s=add();s=add(s,{title:'다른 장소'});const [a,b]=s.candidates;s=action(s,'vote',a.id);s=action(s,'vote',b.id);assert.equal(s.candidates[0].votes.length,1);assert.equal(s.candidates[1].votes.length,1);s=action(s,'vote',a.id);assert.equal(s.candidates[0].votes.length,0);for(const p of s.participants)s=action(s,'vote',a.id,p.id);assert.equal(s.candidates[0].votes.length,5);});
test('PICK cap is 3 across all dates, not per day; unpick frees a slot',()=>{let s=M.create();for(let i=0;i<4;i++)s=add(s,{title:'장소'+i,dayId:i%2?'2026-11-07':dayId});for(const c of s.candidates.slice(0,3))s=action(s,'pick',c.id);assert.throws(()=>action(s,'pick',s.candidates[3].id),/3개/);s=action(s,'pick',s.candidates[0].id);s=action(s,'pick',s.candidates[3].id);assert.equal(s.candidates.filter(c=>c.picks.includes('p1')).length,3);});
test('competition ranking preserves equal-vote ties and no rank for zero votes',()=>{let s=M.create();for(let i=0;i<4;i++)s=add(s,{title:'장소'+i});for(const c of s.candidates.slice(0,2)){s=action(s,'vote',c.id);s=action(s,'vote',c.id,'p2');}s=action(s,'vote',s.candidates[2].id);const r=M.rank(s.candidates);assert.deepEqual(r.map(x=>x.rank),[1,1,3,0]);assert.deepEqual(r.map(x=>x.tied),[true,true,false,false]);});
test('only original proposer may edit/delete; immutable vote identities are not patchable',()=>{let s=add();assert.throws(()=>action(s,'edit',s.candidates[0].id,'p2',{patch:{title:'wrong'}}),/본인/);assert.throws(()=>action(s,'delete',s.candidates[0].id,'p2'),/본인/);s=action(s,'edit',s.candidates[0].id,'p1',{patch:{title:'수정',votes:['p2'],authorId:'p2'}});assert.equal(s.candidates[0].title,'수정');assert.deepEqual(s.candidates[0].votes,[]);assert.equal(s.candidates[0].authorId,'p1');});
test('locked days reject all candidate mutation, slots, comments, votes and confirmation',()=>{let s=add();const id=s.candidates[0].id;s=M.change(s,{type:'day',dayId,patch:{locked:true}},'p1');for(const a of [{type:'vote',id},{type:'pick',id},{type:'comment',id,text:'hello'},{type:'edit',id,patch:{title:'no'}},{type:'delete',id},{type:'confirm',id,dayId,slotId:'morning'},{type:'slot',dayId,slotId:'morning',patch:{enabled:false}},{type:'add',candidate:fixture()}])assert.throws(()=>M.change(s,a,'p1'),/잠/);assert.throws(()=>M.change(s,{type:'day',dayId,patch:{locked:false,status:'vote'}},'p1'),/잠금/);s=M.change(s,{type:'day',dayId,patch:{locked:false}},'p1');assert.equal(action(s,'vote',id).candidates[0].votes.length,1);});
test('confirmation and rain alternatives cannot refer across slots or be identical',()=>{let s=add();s=add(s,{title:'점심',slotId:'lunch'});const [a,b]=s.candidates;s=M.change(s,{type:'confirm',dayId,slotId:'morning',id:a.id},'p1');assert.throws(()=>M.change(s,{type:'rain',dayId,slotId:'morning',id:a.id},'p1'),/다른/);assert.throws(()=>M.change(s,{type:'confirm',dayId,slotId:'morning',id:b.id},'p1'),/같은/);});
test('delete clears confirmation and rain references without affecting unrelated candidates',()=>{let s=add();s=add(s,{title:'우천 후보'});const [a,b]=s.candidates;s=M.change(s,{type:'confirm',dayId,slotId:'morning',id:a.id},'p1');s=M.change(s,{type:'rain',dayId,slotId:'morning',id:b.id},'p1');s=action(s,'delete',a.id);assert.equal(s.days[0].slots[1].confirmedId,null);assert.equal(s.days[0].slots[1].rainId,b.id);s=action(s,'delete',b.id);assert.equal(s.days[0].slots[1].rainId,null);});
test('inactive slots preserve candidates but disappear from route and budget',()=>{let s=add(M.create(),{cost:2500});const id=s.candidates[0].id;s=M.change(s,{type:'confirm',dayId,slotId:'morning',id},'p1');assert.equal(M.budget(s,dayId).total,2500);s=M.change(s,{type:'slot',dayId,slotId:'morning',patch:{enabled:false}},'p1');assert.equal(s.candidates.length,1);assert.equal(M.route(s,dayId).length,0);assert.equal(M.budget(s,dayId).total,0);assert.throws(()=>add(s),/使用|사용/);});
test('unknown costs are not misrepresented as free',()=>{let s=add();s=add(s,{title:'무료 장소',slotId:'lunch',cost:0});for(const c of s.candidates)s=M.change(s,{type:'confirm',dayId,slotId:c.slotId,id:c.id},'p1');assert.deepEqual(M.budget(s,dayId),{total:0,unknown:1,count:2});});
test('a final day must have all enabled slots confirmed; removing a choice reopens voting',()=>{let s=add();assert.throws(()=>M.change(s,{type:'day',dayId,patch:{status:'final'}},'p1'),/모든/);for(const slot of s.days[0].slots)if(slot.id!=='morning')s=M.change(s,{type:'slot',dayId,slotId:slot.id,patch:{enabled:false}},'p1');s=M.change(s,{type:'confirm',dayId,slotId:'morning',id:s.candidates[0].id},'p1');s=M.change(s,{type:'day',dayId,patch:{status:'final'}},'p1');assert.equal(s.days[0].status,'final');s=M.change(s,{type:'confirm',dayId,slotId:'morning',id:null},'p1');assert.equal(s.days[0].status,'vote');});
test('input validation rejects invalid URLs, amounts, coordinates, times, voters and names',()=>{assert.throws(()=>add(M.create(),{mapsUrl:'javascript:alert(1)'}));assert.throws(()=>add(M.create(),{photoUrl:'data:text/html,test'}));assert.throws(()=>add(M.create(),{cost:-1}));assert.throws(()=>add(M.create(),{lat:91,lng:130}));assert.throws(()=>add(M.create(),{lat:30,lng:null}));assert.throws(()=>M.change(M.create(),{type:'slot',dayId,slotId:'morning',patch:{start:'18:00',end:'10:00'}},'p1'));assert.throws(()=>M.change(M.create(),{type:'participants',names:['a','a','c','d','e']},'p1'));assert.throws(()=>add(M.create(),{},'p6'));const bad=add();bad.candidates[0].votes=['p1','p1'];assert.throws(()=>M.validate(bad));});
test('unsafe imports, duplicate IDs and excess PICKs are rejected without mutating originals',()=>{let s=add();const original=JSON.stringify(s);assert.throws(()=>M.change(s,{type:'edit',id:s.candidates[0].id,patch:{cost:-5}},'p1'));assert.equal(JSON.stringify(s),original);const clone=JSON.parse(original);clone.candidates.push(clone.candidates[0]);assert.throws(()=>M.validate(clone),/중복/);const broken=JSON.parse(original);broken.days[0].slots[1].confirmedId='not-found';assert.throws(()=>M.validate(broken));const badVersion={...s,version:2};assert.throws(()=>M.validate(badVersion));});
test('JSON round trip retains comments, votes, bookmarks, bookings and exact times',()=>{let s=add();s=action(s,'comment',s.candidates[0].id,'p2',{text:'반가워요 <img onerror=alert(1)>'});s=action(s,'vote');s=action(s,'pick');s=M.change(s,{type:'bookings',patch:{hotel:'숙소\n체크인 15시'}},'p1');s=M.change(s,{type:'slot',dayId,slotId:'morning',patch:{start:'09:30',end:'11:30'}},'p1');assert.deepEqual(M.validate(JSON.parse(JSON.stringify(s))),s);});
test('maps allow Google shared links and reject lookalike hostnames; viewport is not a place pin',()=>{for(const url of ['https://maps.app.goo.gl/abc','https://goo.gl/maps/abc',M.searchUrl('오사카')])assert.ok(M.safeUrl(url,true));for(const url of ['https://google.com.evil.test/maps','https://example.com/maps','https://google.com/search?q=hi','https://user:pass@google.com/maps'])assert.throws(()=>M.safeUrl(url,true));assert.equal(M.coordinates('https://www.google.com/maps/@34.5,135.5,12z'),null);assert.deepEqual(M.coordinates('https://www.google.com/maps/place/x/data=!3d34.5!4d135.5'),{lat:34.5,lng:135.5});assert.deepEqual(M.coordinates('https://www.google.com/maps/search/?api=1&query=34.5%2C135.5'),{lat:34.5,lng:135.5});});
test('maps URLs are encoded and bounded; routes use explicit modes and stable chronological order',()=>{const long=M.searchUrl('한'.repeat(100),'글'.repeat(300));assert.ok(long.length<=2048);const a=fixture({title:'한'.repeat(100),address:'글'.repeat(300)}),b=fixture({title:'일'.repeat(100),address:'본'.repeat(300)});const u=new URL(M.directionsUrl(a,b,'transit'));assert.equal(u.searchParams.get('api'),'1');assert.equal(u.searchParams.get('travelmode'),'transit');assert.ok(u.href.length<=2048);let s=add(M.create(),{slotId:'lunch'});s=add(s,{slotId:'morning'});for(const c of s.candidates)s=action(s,'vote',c.id);assert.deepEqual(M.route(s,dayId,'leaders').map(r=>r.slot.id),['morning','lunch']);assert.equal(M.route(s,dayId).length,0);});
