/* Run after: npm install --prefix .qa playwright@1.55.1
 * Start a local server in this folder, then: node qa/browser-check.cjs
 * The test uses an isolated browser profile and never the user's regular tabs.
 */
const {chromium}=require('../.qa/node_modules/playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const BASE=process.env.TRIP_TEST_URL||'http://127.0.0.1:8914/';
const KEY='trip-together.osaka.2026.v1';
const OUT=path.resolve('qa-output');
(async()=>{
  await fs.mkdir(OUT,{recursive:true});
  const browser=await chromium.launch({executablePath:process.env.CHROME_BIN||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
  const results=[],errors=[];
  async function check(name,fn){await fn();results.push(name);console.log('PASS '+name);}
  const ctx=await browser.newContext({viewport:{width:390,height:844},locale:'ko-KR',timezoneId:'Asia/Seoul',acceptDownloads:true});
  await ctx.route(/https:\/\/(fonts\.googleapis\.com|fonts\.gstatic\.com|unpkg\.com)\//,r=>r.abort());
  const page=await ctx.newPage();page.on('pageerror',err=>errors.push(err.message));
  page.setDefaultTimeout(7000);
  const data=()=>page.evaluate(k=>JSON.parse(localStorage.getItem(k)),KEY);
  const click=a=>page.locator(`[data-action="${a}"]:visible`).first().click();
  const accept=()=>page.locator('#confirm-dialog [data-action="accept-confirm"]').click();
  const nav=v=>page.locator(`.bottom-nav [data-view="${v}"]`).click();
  async function close(){await page.locator('#panel-dialog [data-action="close-modal"]').first().click();if(await page.locator('#confirm-dialog').isVisible())await accept();}
  async function add(title,{slot='morning',cost='',category='sight',coords=false}={}){
    await page.locator('.bottom-nav .nav-add').click();
    await page.locator('#candidate-slot').selectOption(slot);
    await page.locator('#candidate-title').fill(title);
    await page.locator('#candidate-category').selectOption(category);
    await page.locator('#candidate-cost').fill(String(cost));
    if(coords)await page.locator('#candidate-maps').fill('https://www.google.com/maps/search/?api=1&query=34.6873%2C135.5262');
    else await page.locator('[data-action="generate-link"]').click();
    await page.locator('#candidate-form button[type="submit"]').click();
    await page.locator('#panel-dialog').waitFor({state:'hidden'});
  }
  async function person(id){await click('participants');await page.locator(`[data-action="select-person"][data-person="${id}"]`).click();}
  async function detail(id){await page.locator(`[data-action="detail"][data-id="${id}"]:visible`).first().click();}
  try{
    await page.goto(BASE,{waitUntil:'networkidle'});
    await check('empty mobile board has 8 slots and no fabricated itinerary',async()=>{assert.equal(await page.locator('.slot').count(),8);assert.equal(await page.locator('.candidate').count(),0);assert.match(await page.locator('h1').innerText(),/다섯 명/);await page.screenshot({path:path.join(OUT,'mobile-empty.png'),fullPage:true});});
    await check('no horizontal overflow at 320, 360, 390, 430, 768, 1024 and 1440 px',async()=>{for(const width of [320,360,390,430,768,1024,1440]){await page.setViewportSize({width,height:1000});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'overflow at '+width);}await page.screenshot({path:path.join(OUT,'desktop-empty.png'),fullPage:true});await page.setViewportSize({width:390,height:844});});
    let first,second;
    await check('candidate form creates a persisted place with costs and exact map coordinates',async()=>{await add('산책 후보',{cost:1200,coords:true});let s=await data();assert.equal(s.candidates.length,1);first=s.candidates[0].id;assert.equal(s.candidates[0].cost,1200);assert.equal(s.candidates[0].lat,34.6873);assert.equal(s.candidates[0].lng,135.5262);});
    await check('voting toggles once per person and adds distinct participant votes',async()=>{const button=()=>page.locator(`[data-action="vote"][data-id="${first}"]:visible`).first();await button().click();assert.deepEqual((await data()).candidates[0].votes,['p1']);await button().click();assert.equal((await data()).candidates[0].votes.length,0);await button().click();await person('p2');await button().click();assert.deepEqual((await data()).candidates[0].votes,['p1','p2']);});
    await check('comments escape HTML and an unfinished comment survives a vote',async()=>{await detail(first);await page.locator('#comment-text').fill('<img src=x onerror="window.xss=1"> 의견이에요');await page.locator('.comment-form button[type="submit"]').click();assert.equal((await data()).candidates[0].comments.length,1);assert.equal(await page.evaluate(()=>window.xss),undefined);assert.match(await page.locator('.comments').innerText(),/<img src=x/);await page.locator('#comment-text').fill('작성 중인 메모');await page.locator('#panel-dialog [data-action="vote"]').click();assert.equal(await page.locator('#comment-text').inputValue(),'작성 중인 메모');await page.locator('#comment-text').fill('');await page.locator('#panel-dialog [data-action="pick"]').click();assert.deepEqual((await data()).candidates[0].picks,['p2']);});
    await check('explicit confirmation is separate from voting and updates the budget',async()=>{await page.locator('#panel-dialog [data-action="confirm"]').click();await accept();assert.equal((await data()).days[0].slots[1].confirmedId,first);await close();assert.match(await page.locator('.budget-amount').innerText(),/1,200/);});
    await check('same-slot alternatives support ties and a different rainy-day choice',async()=>{await add('카페 후보',{category:'cafe',cost:900});second=(await data()).candidates[1].id;await page.locator(`[data-action="vote"][data-id="${second}"]:visible`).first().click();assert.equal(await page.locator('#slot-morning .rank').filter({hasText:'공동 1위'}).count(),2);await detail(second);await page.locator('#panel-dialog [data-action="rain"]').click();await accept();assert.equal((await data()).days[0].slots[1].rainId,second);await close();});
    await check('search, categories and personal vote screens work',async()=>{await nav('candidates');assert.equal(await page.locator('.candidate-tile').count(),2);await page.locator('#candidate-search').fill('없는장소');assert.equal(await page.locator('.candidate-tile').count(),0);await click('clear-filters');await page.locator('[data-action="category"][data-category="cafe"]').click();assert.equal(await page.locator('.candidate-tile').count(),1);await nav('mine');assert.match(await page.locator('.my-banner').innerText(),/여행자 2/);assert.match(await page.locator('.pick-budget').innerText(),/1/);});
    await check('day lock blocks changes; disabled slots retain data; invalid settings are atomic',async()=>{await nav('board');await click('day');await page.locator('[name="enabled-breakfast"]').uncheck();await page.locator('[name="start-morning"]').fill('09:30');await page.locator('[name="end-morning"]').fill('11:30');await page.locator('button[name="mode"][value="lock"]').click();assert.equal((await data()).days[0].locked,true);assert.equal(await page.locator('.slot').count(),7);await page.locator('.bottom-nav .nav-add').click();assert.equal(await page.locator('#panel-dialog').isVisible(),false);await click('day');await click('unlock');await accept();const prior=JSON.stringify(await data());await page.locator('[name="start-morning"]').fill('18:00');await page.locator('button[name="mode"][value="save"]').click();assert.equal(JSON.stringify(await data()),prior);assert.match(await page.locator('.form-error').innerText(),/종료 시간/);await page.locator('[name="start-morning"]').fill('09:30');await page.locator('#day-status').selectOption('final');await page.locator('button[name="mode"][value="save"]').click();assert.match(await page.locator('.form-error').innerText(),/모든 시간대/);await page.locator('#day-status').selectOption('vote');await page.locator('button[name="mode"][value="save"]').click();});
    await check('only the proposer sees edit/delete controls',async()=>{await person('p1');await detail(second);assert.equal(await page.locator('#panel-dialog [data-action="edit"]').count(),0);assert.equal(await page.locator('#panel-dialog [data-action="delete"]').count(),0);await close();await detail(first);assert.equal(await page.locator('#panel-dialog [data-action="edit"]').count(),1);await close();});
    await check('JSON export works, invalid imports are rejected and valid replacement needs confirmation',async()=>{await click('settings');const dl=page.waitForEvent('download');await page.locator('#panel-dialog [data-action="export"]').click();const download=await dl;await download.saveAs(path.join(OUT,'test-backup.json'));const backup=JSON.parse(await fs.readFile(path.join(OUT,'test-backup.json'),'utf8'));assert.equal(backup.candidates.length,2);const original=JSON.stringify(await data());await page.locator('#import-file').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"version":99}')});await page.locator('.form-error').filter({hasText:'지원'}).waitFor();assert.match(await page.locator('.form-error').innerText(),/지원/);assert.equal(JSON.stringify(await data()),original);backup.participants[2].name='세 번째 여행자';await page.locator('#import-file').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await page.locator('#confirm-dialog').waitFor({state:'visible'});assert.equal((await data()).participants[2].name,'여행자 3');await accept();assert.equal((await data()).participants[2].name,'세 번째 여행자');});
    await check('sample experience is isolated from the real browser board',async()=>{const original=JSON.stringify(await data());await click('settings');await page.locator('#panel-dialog [data-action="demo"]').click();assert.equal(await page.locator('.demo-notice').count(),1);assert.equal(JSON.stringify(await data()),original);await page.screenshot({path:path.join(OUT,'mobile-demo.png'),fullPage:true});await page.setViewportSize({width:1440,height:1050});await page.screenshot({path:path.join(OUT,'desktop-demo.png'),fullPage:true});await page.setViewportSize({width:390,height:844});await page.locator('.candidate [data-action="vote"]:visible').first().click();assert.equal(JSON.stringify(await data()),original);await click('exit-demo');assert.equal(JSON.stringify(await data()),original);});
    await check('offline map loading fails gracefully and preserves real directions links',async()=>{await nav('map');await page.locator('[data-action="date"][data-day="2026-11-06"]').click();await page.locator('.map-placeholder').filter({hasText:'배경 지도를 불러오지 못했어요'}).waitFor();assert.equal(await page.locator('.route-card').count(),1);await page.locator('[data-action="map-mode"][data-mode="leaders"]').click();await page.screenshot({path:path.join(OUT,'mobile-map-fallback.png'),fullPage:true});});
    await check('same-browser tabs synchronize and reject stale form submissions',async()=>{await nav('board');await click('bookings');await page.locator('#booking-hotel').fill('첫 탭의 아직 저장하지 않은 메모');const tab=await ctx.newPage();await tab.goto(BASE,{waitUntil:'networkidle'});await tab.locator('[data-action="bookings"]:visible').first().click();await tab.locator('#booking-hotel').fill('다른 탭에서 저장한 숙소');await tab.locator('[data-form="bookings"] button[type="submit"]').click();await page.waitForFunction(k=>JSON.parse(localStorage.getItem(k)).bookings.hotel==='다른 탭에서 저장한 숙소',KEY);await page.waitForTimeout(150);await page.locator('[data-form="bookings"] button[type="submit"]').click();assert.match(await page.locator('.form-error').innerText(),/다른 변경/);assert.equal((await data()).bookings.hotel,'다른 탭에서 저장한 숙소');await close();await tab.close();});
    await check('reload restores saved board and edited slot times',async()=>{await page.reload({waitUntil:'networkidle'});assert.equal((await data()).candidates.length,2);assert.equal((await data()).days[0].slots[1].start,'09:30');assert.equal(await page.locator('.slot').count(),7);});
    await check('standalone file can create a candidate and persist it across reload',async()=>{const fileCtx=await browser.newContext({viewport:{width:390,height:844}});await fileCtx.route(/https:\/\/fonts\./,r=>r.abort());const p=await fileCtx.newPage();p.on('pageerror',err=>errors.push('file: '+err.message));await p.goto(pathToFileURL(path.resolve('index.html')).href,{waitUntil:'networkidle'});assert.equal(await p.locator('.slot').count(),8);await p.locator('.bottom-nav .nav-add').click();await p.locator('#candidate-title').fill('단일 HTML 저장 테스트');await p.locator('[data-action="generate-link"]').click();await p.locator('#candidate-form button[type="submit"]').click();await p.locator('#panel-dialog').waitFor({state:'hidden'});await p.reload({waitUntil:'networkidle'});assert.equal(await p.evaluate(k=>JSON.parse(localStorage.getItem(k)).candidates.length,KEY),1);await fileCtx.close();});
    await check('corrupted saved data is preserved rather than silently overwritten',async()=>{const brokenCtx=await browser.newContext({viewport:{width:390,height:844}});await brokenCtx.route(/https:\/\/fonts\./,r=>r.abort());const p=await brokenCtx.newPage();await p.addInitScript(k=>localStorage.setItem(k,'{broken'),KEY);await p.goto(BASE,{waitUntil:'networkidle'});assert.match(await p.locator('.storage-notice').innerText(),/原本|원본/);assert.equal(await p.evaluate(k=>localStorage.getItem(k),KEY),'{broken');await p.locator('.bottom-nav .nav-add').click();await p.locator('#candidate-title').fill('저장 안돼야 함');await p.locator('[data-action="generate-link"]').click();await p.locator('#candidate-form button[type="submit"]').click();assert.equal(await p.evaluate(k=>localStorage.getItem(k),KEY),'{broken');await brokenCtx.close();});
    assert.deepEqual(errors,[],'browser JavaScript errors');
    console.log('PASS zero browser JavaScript errors');
    await fs.writeFile(path.join(OUT,'browser-results.json'),JSON.stringify({passed:results.length,results,errors},null,2));
    console.log('TOTAL '+results.length+' browser checks passed.');
  }catch(err){console.error(err);await page.screenshot({path:path.join(OUT,'failure.png'),fullPage:true}).catch(()=>{});await fs.writeFile(path.join(OUT,'browser-results.json'),JSON.stringify({passed:results.length,results,errors,failure:String(err)},null,2));process.exitCode=1;}
  finally{await browser.close();}
})();
